server:
  port: ${SERVER_PORT}

dagents:
  core:
    app-name: ${DAGENTS_CORE_APP_NAME}
    environment: ${DAGENTS_CORE_ENVIRONMENT}
    control-service-url: ${DAGENTS_CORE_CONTROL_SERVICE_URL}
    lma-url: ${DAGENTS_CORE_LMA_URL}
    gma-url: ${DAGENTS_CORE_GMA_URL}
    model-service-url: ${DAGENTS_CORE_MODEL_SERVICE_URL}
    pipeline-service-url: ${DAGENTS_CORE_PIPELINE_SERVICE_URL}
