"""Typed domain models for the Global Monitoring Agent."""

from agents.common.domain.models import (
    AgentIdentity,
    AgentSnapshot,
    CommandStatus,
    DeploymentPlan,
    DeploymentSyncRequest,
    DeploymentSyncResponse,
    DesiredDeploymentRequest,
    DispatchedRun,
    FleetOverview,
    HeartbeatRequest,
    HeartbeatResponse,
    RegisterRequest,
    RegisterResponse,
    RunDispatchRequest,
    TelemetryAck,
    TelemetryEnvelope,
    TelemetryPoint,
    TelemetrySummary,
)

__all__ = [
    "AgentIdentity",
    "AgentSnapshot",
    "CommandStatus",
    "DeploymentPlan",
    "DeploymentSyncRequest",
    "DeploymentSyncResponse",
    "DesiredDeploymentRequest",
    "DispatchedRun",
    "FleetOverview",
    "HeartbeatRequest",
    "HeartbeatResponse",
    "RegisterRequest",
    "RegisterResponse",
    "RunDispatchRequest",
    "TelemetryAck",
    "TelemetryEnvelope",
    "TelemetryPoint",
    "TelemetrySummary",
]
